### ISSUE TITLE
Master System Crop Overscan??? 

### ISSUE THREAD

**Issue by zcstrife** [libretro/Genesis-Plus-GX#116]
Hello everyone,

I can't figure how to crop overscan of the master system. I'm really annoyed by the bar on the left. Even though I understand it is what the master system actually output, on a CTR TV we weren't able to see it.
Is there any way to crop overscan with Genesis Plus Gx?
I know picodrive can do this, but it has many flaws and is far from being as good as Genesis Plus Gx.

**Comment by hizzlekizzle** [comment]
GenPlusGX has core options for overscan cropping. If that doesn't get you covered, you can also use the image-adjustment shader to do additional cropping/masking.

**Comment by zcstrife** [comment]
How is it called though? I can't find it in the options.
Is this "borders" ? Because "borders" doesn't crop correctly. Just like on the NES, there's a little more border on the left. Picodriver make the cropping correctly.
But I guess you're right, I could create an overlay and set video resolution to custom to adjust it.

**Comment by hizzlekizzle** [comment]
Yeah, borders. I haven't used genplusgx standalone on Wii to see if it has different cropping behavior for SMS. If so (that is, if it's already setup somewhere in the core), we could just tap into that. Otherwise, we'd have to do some magic in the libretroization.

**Comment by ekeeke** [comment]
That left bar is not part of overscan (or borders) and was actually quite visible on most CRT TVs because it's part of Master System active screen (256 pixels wide). It could be switched ON by games to hide graphics glitches when doing horizontal scrolling but is usually OFF in many games so it would be wrong to say that this bar happens all the time.

Also, since it's game dependent and can be switched on/off anytime, unless you want to hide part of the screen even when it's not there, 'cropping' would need to be done dynamically, resulting in video width switching between 256 and 248 pixels.

**Comment by Sanaki** [comment]
Given that this bar is left side only, is there a reason the core option to hide it crops both sides by eight pixels? Seems like the right side should be left intact.

**Comment by ds22x** [comment]
Because due to how the screen coding works, I couldn't exactly shift the screen to the left, only stretch it equally on both sides.

**Comment by Sanaki** [comment]
Ah. That's unfortunate, but it makes sense. Suppose I'll just use the shader solution instead then.

**Comment by ds22x** [comment]
I mean, if anyone with a better understanding would want to take a look at it, I'd appreciate it, but the best I can do is stretch the screen (which, depending on the game, doesn't always look that bad anyway).
