### ISSUE TITLE
Onslaught (USA) not running (Genesis)

### ISSUE THREAD

**Issue by nikkoman** [libretro/Genesis-Plus-GX#122]
Probably the only ROM that doesn't load on v1.7.4 7104058

Edit: the ROM loads if bootrom is disabled. Any idea why?

**Comment by ekeeke** [comment]
http://www.sega-16.com/forum/showthread.php?22717-Onslaught

It's one of the early Genesis title that wasn't officialy licensed by Sega and fail to run on models with TMSS lockout.

**Comment by ekeeke** [comment]
Some more games that fail to load with TMSS

https://segaretro.org/TradeMark_Security_System

**Comment by nikkoman** [comment]
Interesting :)

Are there any Game Gear or Master System titles that won't run with a BIOS?

I use them for a more authentic feeling but if they sacrifice compatibility, I'd rather remove them...

**Comment by ekeeke** [comment]
The only incompatibilities I know are between US/European Master System BIOS and japanese exclusive Mark III or Master System games since they usually don't have a valid ROM header as expected by those BIOS but the emulator should normally autodetect the region and pick the suitable BIOS (there is one configurable for each three regions).

Game Gear BIOS is only authentic if you had one of the later model, original models don't have any. Again, it checks for valid ROM header and verify the checksum but I think japanese Game Gear games had same ROM standards as western games so it shouldn't have any issue with them.

See here for more details on available BIOS
http://www.smspower.org/Development/BIOSes

**Comment by ekeeke** [comment]
This can be closed by the way as it's a non-issue.

**Comment by nikkoman** [comment]
Thank you for this information 🥇
