### ISSUE TITLE
Low volume for Sonic jumps in any Sonic related game

### ISSUE THREAD

**Issue by nad53** [libretro/Genesis-Plus-GX#176]
Greetings people.
I have been looking for a while but couldn't find anybody requesting a fix to this issue on Genesis Plus GX for any megadrive Sonic-like game.
Basically the problem is any jump you execute in sonic games will sound way quieter than use to be in any other platform I have ever listened this sound effect, either being listened on Sonic Mania (2017 game) or known emulators like  Gens, Kega Fusion. I'm guessing it's a sound-frequency issue.
I'm concerned there are people out there saying Genesis Plus GX is more accurate than Kega Fusion in sound emulation.

You can make a test between  Retroarch + genesis plus gx with any sonic game and Kega fusion. Jump sound effect can be heard way better in Kega fusion or Blastem  or Gens. I used to have a Megadrive console some years ago and I remember clearly that sonic jumps didn't sound as quiet as use to do with Genesis plus GX. I think that's an issue with this core. Game experience truly is affected for it.

I would appreciate if you can either fix this issue or set an option available for this core to make the frequency related to sound as good as Kega fusion or Sonic Mania  because game experience in my opinion changes a lot and I'm sure for a lot of people too.

Thanks.

Edit: I have tested back again this issue and even on PicoDrive or Steam emulator, sonic's jump sounds way louder (which is perfect) which fits to the current volume level of any other sound effects.

**Comment by hizzlekizzle** [comment]
Have you tried the nuked sound core (under 'mega drive / genesis fm')?

**Comment by nad53** [comment]
> 
> 
> Have you tried the nuked sound core (under 'mega drive / genesis fm')?

Hi there. For sure buddy, either both of nuked sound cores. This is a very unsual low volume for Jump sound effect. I have tried now recently with Mednafen's megadrive core too and it does sound louder as should be.

**Comment by ekeeke** [comment]
Sonic games all use PSG (Master System like) sound chip for jumps sound so it has nothing to do with FM chip emulation accuracy or 'frequency issues'.

You can adjust PSG sound level against FM sound level using config.psg_preamp and config.fm_preamp settings. Those settings are actually set by default respectively to 150% vs100% and those factors (with sound chips fixed max output levels) were adjusted to match my MD1 VA4 model sound ouput (precisely using Sonic 1 jump sound as reference) but it might be different on other models or clones (or other emulators) you are used to, hence why it was made as a configurable settings (the Wii/GC original port let you adjust FM/PSG balance). 

In libretro port, those settings are not modificable and hard-coded to default value but there is nothing preventing you to add them in core settings exposed in retroarch if you want (I think the main reason I didn't exposed them initially were that libretro core settings were not really suited for variable range values line these but maybe this has changed since).

**Comment by hizzlekizzle** [comment]
those options are exposed now, as of #178 so if @nad53 can test and close the issue, I think we're all set.

**Comment by nad53** [comment]
I talked to some guys on retroarch's community and it does work flawlessly thus far @hizzlekizzle  @ekeeke . Thank you for all your help and patience. Outstanding work there with this core.
