### ISSUE TITLE
Stutter/Micro freeze during Sega CD FMV

### ISSUE THREAD

**Issue by Smannesman** [libretro/Genesis-Plus-GX#186]
Using Retroarch 1.7.8v2 and Genesis Plux GX 1.7.4 ba9556a I experience slight freezes during the Popful Mail cutscenes. 
This video shows the issue: [https://youtu.be/aEnYaU9O5UU](https://youtu.be/aEnYaU9O5UU)
I've tried changing the BIOS, the audio emulation, VSync on/off, different images of the game.
Also tried different harddrives, both SSD and HDD.
The issue does not occur in the Picodrive Retroarch core nor in Kega Fusion.

**Comment by darksaviorx** [comment]
I'll add that this bug has been there for a few years now, but I completely forgot to make a post about it. I can also verify the issue and that it doesn't exist on picodrive.

**Comment by ekeeke** [comment]
Yes, this bug exists since the first release of the emulator with Sega CD support and is not specific to the libretro core (also occu in standalone version).

For the record, it is due to the way I handled Sega CD Timer interrupt which is not as precise as original hardware and was only possibly triggered at line granularity (it was mostly done this way initially because it was simpler and more optimized this way, while still apparently working fine with all games that use Sega CD timer feature... well, except this one during FMV).

It should be fixed by this commit (https://github.com/ekeeke/Genesis-Plus-GX/commit/e66b7bc83d2ef98feeb5f40b2ebebd55f727406e) I just made in my own repository: you will need to wait until this is backported into libretro repository to validate it and close the issue (or check my own libretro win32 build under https://github.com/ekeeke/Genesis-Plus-GX/tree/master/builds).
