### ISSUE TITLE
Genesis Plus GX and Mega CD games: audio doesn’t seem to sync properly

### ISSUE THREAD

**Issue by Galdelico** [libretro/Genesis-Plus-GX#189]
Hello, I’m experiencing an odd issue, while running Mega CD and SEGA-CD games through Genesis Plus GX, on RetroArch v1.7.8 (v4). I'm on Windows 10, version 1903.

Premise: I use verified redumps of games I own in my retrogame collection, so I know how they behave pretty well and I noticed a couple of quirks right away.

First, I launched _Annet Futatabi (Japan)_, which seemed to work prefectly - the speech during cutscenes sounded synced to me - until a split-second long pause happened, right at the beginning of the first stage. It repeats in every level, and of course there are no pauses in the actual game. 
Same thing with _Bari-Arm (Japan)_: no recurring pauses at the start of each level, but there is a slight sound delay during the Human logo's animation: the jingle gets cut quite abruptly, a second or so before its time, instead of playing it to the end. The whole opening and also the transformation cutscene after each bossfight appear to be slightly delayed.

My laptop should have the specs to ensure perfect emulation, and in fact the games run perfectly fine. What’s weird, it doesn’t seem to change even if I try different combinations:

A) RetroArch on my internal, data hard-drive + Bari-Arm on the same HDD
B) same + Bari-Arm on the Windows SSD unit
C) same + Bari Arm (not the Redump version, but instead the CUE/CCD/SUB/image package) on an external USB Seagate Portable drive

I also tried to convert the cue/bin folder into a CHD file, and to swap different Japanese BIOS files (MCD, MCD2, etc…). No matter what, the amount of sound delay remains exactly the same: doesn’t get better or worse. 

Any idea about what is causing this?
Thanks in advance! ^_-

**Comment by ToniBC** [comment]
I observe the same problem in Bari-Arm, the logo has a slight delay of approx 1s, seems to be related to the loading of the audio track. I think it would be necessary to implement some more precise synchronization in the audio CD.

**Comment by Galdelico** [comment]
Thanks for looking into it!

**Comment by ekeeke** [comment]
This seems to be related to CD access/seek time emulation: disabling it fixes the sound delay in Bari Arm with Human logo's animation (I did not test other games). It is required by some games (mostly Wolfteam's games)  that freeze on startup otherwise if there is no seek delay emulated. 

In Bari Arm, the games send a 'play' command to play last CDDA track (track #19 starting at 34:10:71) which is at the end of the disc and ~154000 sectors away from current sector so there should definitively be some significant seek time delay: my emulation model adds 79 interrupts latency (approx. 1s since those are 75Hz interrupts) but it seems zero is required to totally avoid the sound delay. It seems unlikely there is zero delay on real hardware when seeking this much far on the disc so if you can confirm that sound effect delay does not occur on real hardware, this means there is something else wrongly emulated.

Out of curiosity, could you try this game in Byuu emulator (https://byuu.itch.io/byuu) which also emulates CD access/seek time apparently but with a different (supposedly more accurate) model ?

**Comment by ekeeke** [comment]
The issue with Bari Arm intro logo was fixed by this commit in my repository: https://github.com/ekeeke/Genesis-Plus-GX/commit/18fca131425698c77914e7dfe79ba6d723bd674f

You can test win32 libretro core build in my repository (under https://github.com/ekeeke/Genesis-Plus-GX/tree/master/builds) or wait for the commit to be pulled in libretro repository  to confirm it fixes all your sync issues.

**Comment by Galdelico** [comment]
> The issue with Bari Arm intro logo was fixed by this commit in my repository: [ekeeke@18fca13](https://github.com/ekeeke/Genesis-Plus-GX/commit/18fca131425698c77914e7dfe79ba6d723bd674f)
> 
> You can test win32 libretro core build in my repository (under https://github.com/ekeeke/Genesis-Plus-GX/tree/master/builds) or wait for the commit to be pulled in libretro repository to confirm it fixes all your sync issues.

Hi @ekeeke ! Sorry for the VERY late reply.
First of all, thank you once again! I didn't have the chance to test it with Byuu yet, but I just tried the latest release of RetroArch (1.8.5) with your modified Genesis Plus X core. I usually download the 64bit version of RA, so this time I got the 32bit one.

Bari Arm works perfectly, now. It's 100% accurate with what I can see on real hardware, with my Japanese original copy.

Having said that, though, I noticed how Annet Futatabi - which had similar sync issues - now locks up systematically during (or straight after) the initial cutscene. I tried a regular ISO and also the latest redump, and the results are the same with both. 
Do you know if there is any specific setting to toggle, in Genesis Plus X, with the games that behave like that?

Thanks once more! ^_-

**Comment by ekeeke** [comment]
No, there isn't any option related to game compatibility, all games should be compatible as they are with original hardware. If they freeze, this is due to an emulation bug or inaccuracy. Since I didn't retested all games after this commit, it is indeed possible it caused a regression with other games, that's quite common. I will have a look at this game.

**Comment by ToniBC** [comment]
I have tried "Annett Futatabi" and it does not crash in the intro or after, I left it until I have control of the character and everything seems to be going correctly.

The game "Android Assault: The Revenge of Bari-Arm!" It seems that it is better synchronized, I do not know if it is like the real system, because I do not have it to check, but it seems that it improved.

Everything in Retroarch x64 (nightly and update cores) and Windows 10 (everything as of the date of this post).

**Comment by Galdelico** [comment]
@ToniBC , I'll give it another go following your setup: last night, I tried the latest, stable 64bit version, with the updated Genesis Plus X core, and it was exactly the same as before. Same cut in Bari Arm, at the same exact point. I'm on Win10 too.
Simply replacing the stock dll with the modified Win32 one @ekeeke provided, resulted in an error.

I'll try the nightly version right now, and see if it makes any difference.

Thank you guys!

**Comment by ekeeke** [comment]
I don't think this repository is up-to-date with my latest change so the retroarch nightly core is still the old version with logo animation sound starting/ending too early

**Comment by Galdelico** [comment]
> I don't think this repository is up-to-date with my latest change so the retroarch nightly core is still the old version with logo animation sound starting/ending too early

Yeah, it looks the same as before, to me. Everything works, but sync issues still persist.
On the other hand, Annet Futatabi keeps freezing, using the Win32 stable version of RetroArch + your modified Genesis Plus X core. 
On top of that, I tested Final Fight CD and Keyo Yugekitai - both NTSC-J - and they both work perfectly, exactly as they do on actual hardware.

**Comment by ekeeke** [comment]
OK, it looks like Annet Futatabi is kinda like Radical Rex and require CDD to return "playing" status for a few interrupts before CD sectors actually start being played. Adding one extra interrupt delay fixed the freeze during at the end of intro (also froze if you skipped the intro): https://github.com/ekeeke/Genesis-Plus-GX/commit/33a43e34c1d2b018ea768a011f3b1619f7fc5bc3

Until these get merged by libretro people, you can test using my own win32 libretro core build that can be found at the usual place:  https://github.com/ekeeke/Genesis-Plus-GX/tree/master/builds

**Comment by Galdelico** [comment]
They both work great now, thank you SO much!
This makes me wish even more Genesis Plus GX would also support 32X... Picodrive on RetroArch isn't good, and having to use the outdated, stand-alone Fusion isn't really ideal anymore.

Thanks again!

**Comment by ekeeke** [comment]
Ok. If this issue is fixed, please don't forget to close it.

**Comment by Galdelico** [comment]
Sure thing, massive thanks once again!
