### ISSUE TITLE
Links external zlib

### ISSUE THREAD

**Issue by iKarith** [libretro/Genesis-Plus-GX#20]
This is a no-no.

**Comment by ekeeke** [comment]
What does that mean ?

**Comment by iKarith** [comment]
Just what it says: GenPlus uses zlib, but doesn't build it in to the 
core.  That means you have to have it installed on your computer or 
it won't work.  Probably you do, but libretro cores should not 
require anything other than a player so that they can run in a secure 
"sandbox".  In fact, a genesis core should probably not use zlib at 
all because the player handles zipped files.

Joseph

**Comment by ekeeke** [comment]
This is actually much clearer than initial statement.

The core however does not uses zlib and the libretro port does not have zip support implemented in libretro.c so there is nothing to fix in the core, hence my question what was a "no-no".

If you are referring to 08c955f6120caacc8ef5d31365b98a1912255db9, then it was simply an error in libretro Makefile which was linking to zlib although it was not needed anywhere.

Since this was fixed, I guess you can close this issue to avoid confusion.
