### ISSUE TITLE
Add per-sound channel individual volume core options

### ISSUE THREAD

**Issue by eadmaster** [libretro/Genesis-Plus-GX#223]
This is meant to ["fix" games having unbalanced SFX vs the BGM](https://eadmaster.altervista.org/wordpress/archives/90).

Will need to add separate options for the PSG and Yamaha chips.

**Comment by eadmaster** [comment]
I am going to try implementing this myself starting with the SMS PSG.
Simply adding an on/off switch for the singular channels seems trivial, but i'll try with  volume scaling as well. If you have any suggestion please post here.

**Comment by eadmaster** [comment]
First addition made for the PSG chip, please review it while i move to the Yamaha chips...

**Comment by eadmaster** [comment]
UPDATE2: added options for the MegaDrive/Genesis FM chip too!

The Master System FM (YM2413) chip still left, but this has a lower priority for me.

Please review the code in my fork before i sumbit the first PR.

**Comment by eadmaster** [comment]
UPDATE3: still need some help to scale the volume of the noise channel on the PSG chip.

**Comment by ekeeke** [comment]
The reason it does not work properly for PSG channels is that, since config.psg_ch_volumes[i] are unsigned int, not float, setting it to a value inferior to 100 and dividing it by 100 will always gives you 0 as a result. So basically, anytime you set one psg channel below 100%, you are actually muting it.

The modified code in psg_config should  be corrected like this for it to work as you expect:
`  psg.chanAmp[i][0] = ((preamp * config.psg_ch_volumes[i]) / 100) * ((panning >> (i + 4)) & 1);`

so that the division occurs after multiplying individual channel volume by preamp value.

Also, forcing delta value update whatever the current output level when your channel volume is below 100 is incorrect and should be removed for correct emulation behavior.

Finally, if you want this to be merged upstream, you will need to isolate and enclose your core modifications using #IFDEF USE_PER_SOUND_CHANNELS_CONFIG / #ENDIF for example, so the core still compile fines in non-libretro ports that don't have your additional config data defined and don't need this hack.

**Comment by eadmaster** [comment]
> So basically, anytime you set one psg channel below 100%, you are actually muting it.

For some reason the tone PSG channels were scaling correctly the volume, and since i couldn't figure out the reason why the noise channel didn't i started making experiments...

> Finally, if you want this to be merged upstream, you will need to isolate and enclose your core modifications using #IFDEF USE_PER_SOUND_CHANNELS_CONFIG / #ENDIF for example, so the core still compile fines in non-libretro ports that don't have your additional config data defined and don't need this hack.

Actually my initial idea was to init the volume arrays with 100 values and then do the volume scaling only if the frontend override these values instead of using prepocessor vars.

Btw i've done all the changes you suggested and everything seems to work fine.
Since you already confirmed there should be no side-effects with these changes i'll send a PR soon.

**Comment by eadmaster** [comment]
UPDATE: i've just pushed a first implementation of the SMS FM (YM2413) channel volume scaler, please review!

**Comment by ekeeke** [comment]
A few remarks:
1) please do not use __LIBRETrO__ specific defines in core sourcecode, so that non-libretro ports can still support this hack if they want by setting specific define in their Makefile. Using a more generic #ifdef as initially proposed is a better long term solution. You only need to had -Dxxxxx in Makefile.libretro core defines, along with other core specific defines (like the one allowing cpu overclocking or sprites limit removal hacks)
2) in PSG code, a cleaner solution would be to add
`#ifdef xxxx
preamp = (preamp * config.psg_ch_volumes[i]) / 100;`
in the loop before updating chan_amp[i]

I didn't looked at your ym2413 core modifications yet.

**Comment by eadmaster** [comment]
> Please do not use LIBRETrO specific defines in core sourcecode, so that non-libretro ports can still support this hack if they want by setting specific define in their Makefile. Using a more generic #ifdef as initially proposed is a better long term solution. You only need to had -Dxxxxx in Makefile.libretro core defines, along with other core specific defines (like the one allowing cpu overclocking or sprites limit removal hacks)

I see, it definitively makes sense, i am changing them now.

I am also adding a switch to hide all new audio core options like snes9x has.

**Comment by eadmaster** [comment]
Please confirm me my latest changes are ok, so i can submit a PR for this...

**Comment by eadmaster** [comment]
nevermind, i've just sent the PR, comment there if you want.
