### ISSUE TITLE
  Jerky scrolling on some Master System games with Audio Sync On

### ISSUE THREAD

**Issue by pegonma** [libretro/Genesis-Plus-GX#244]
I have been trying to play Sonic 2 (8bits) on the Master System, but scrolling is not smooth at all when playing (just move for 2 seconds in the first level to see it), when audio sync is on. This is not due to the original limitations of the hardware setting CPU speed to 200% fixes the slowdowns in the game, but does not solve the jerky scrolling). Disabling Audio Sync makes the scrolling perfectly smooth, however then the sound is just awful... There must be a way to have smooth scrolling and somewhat fine audio playback : it works fine on Sonic 1.

**Comment by ekeeke** [comment]
Sonic 2 is a PAL exclusive game on Master System so the emulator forces  PAL timings by default when it is loaded, which coukd explain your video issues as the refresh rate will be 50hz instead of 60hz.

You can force "System Region" to NTSC-U in core settings but it might cause some glitches or inaccuracies as the game requires PAL timings.

**Comment by pegonma** [comment]
@ekeeke Thank you for your answer, you are absolutely right. I didn't know Sonic 2 8-bits was a PAL exclusive game, and cannot be played without glitches with NTSC-U timings. Switching to PAL region fixed the issue.
