### ISSUE TITLE
Ogg audio is not working on Android

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/Genesis-Plus-GX#28]
I converted the .wav sound files to .ogg, and it's working well on my laptop, but not on Android. I took a brief look and it seems tremor is enabled in the Android.mk, so I really don't know what's happening here.

When I play any ogg music in the sega cd bios, I can hear only noise.

**Comment by ekeeke** [comment]
I got an email about this issue but I'm afraid I have no idea why the same files would work on the Windows port and not Android one. An issue with OGG playback when used within cuesheet file was fixed some time ago but this seems different here. If those exact same files work on every other platforms (also remember OGG files should be using 44,1 kHz stereo format), then it's likely a platform or compiler specific issue.

From libtremor README: 
https://github.com/libretro/Genesis-Plus-GX/raw/master/core/tremor/README

>Currently, the source implements playback in pure C on all platforms
except ARM, where a [currently] small amount of assembly (see
asm_arm.h) is used to implement 64 bit math operations and fast LSP
computation.  If building on ARM without the benefit of GNU build
system tools, be sure that '_ARM_ASSEM_' is #defined by the build
system if this assembly is desired, else the resulting library will
use whatever 64 bit math builtins the compiler implements.

I am not sure if this is the reason it does not work and have no mean to build retroarch for Android but it might still be worth using this for ARM platforms, at least for performance reasons. 

PS: Not sure either if anyone from Retroarch are still lurking here since all the other issues have been left opened despite being fixed for a long time.

**Comment by ekeeke** [comment]
Not sure if this is still an on-going issue but you might also want to  ask this guy https://m.youtube.com/watch?v=S5oLucN-DDA

>I've compiled my own build of Retroarch for Android with the following modifications:
>- Fixed Vorbis support in Genesis-Plus-GX core

**Comment by diablodiab** [comment]
I've submitted a pull request with the fix.

**Comment by sergiobenrocha2** [comment]
It's working!!! Thanks!
