### ISSUE TITLE
Limited to 1 CD track at a time?

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/Genesis-Plus-GX#30]
This is something I noticed in Dennin Aleste (Robo Aleste in US version):

When the game starts the main character digit voice is not playing (it should be like this https://youtu.be/PrcRnnOdXew?t=272 ).
But when you go in the sound test mode you can hear it.

The sound test mode plays just that track you ask, no music in background, unlike the game itself.

**Comment by ekeeke** [comment]
It's technically impossible for any CD player to play more than one CD-DA track simultaneously and Mega CD is no exception.

That video is clearly a montage, it could be they only captured video and then added audio tracks ripped from the CD on the video. Are you 100% sure that the digit voice should be playing here?

What is sure is that it is technically impossible that this digit voice (which is actually the 2nd track of the disc, i.e first audio track) is played at the same time as the BGM (which is the 3rd track of the disc, i.e 2nd audio track).

What could happen is that the 1st audio track (digit voice) is played first, then 2nd audio track (BGM) is started and some emulation bug makes it so that the first one is skipped or the second one starts too early. However the same happens in Kega Fusion and nothing looks suspicious in the emulator debug output so unless someone provides a recording coming straight from Mega CD hardware, I assume this is what happens on real hardware.

**Comment by Tatsuya79** [comment]
I just heard the audio tracks and noticed several were those intro lines at the beginning of each stages.
That's so strange they were done and left like that.

Anyway thanks for the answer and I'll use the other repo next time.
