### ISSUE TITLE
Galactic Protector (SMS) - Player 2 paddle jerky movement

### ISSUE THREAD

**Issue by Widge-5** [libretro/Genesis-Plus-GX#340]
Galactic Protector is one of the handful of Sega Master System games that use the Japanese-exclusive Paddle controller, and Galactic Protector is the only 2-player game (afaik).  For the most part the implementation of this paddle controller in lr-genesis-plus_gx is pretty good, but with one exception.

The movement of the Player 2 sprite around the globe is very jerky, particular when compared with the smooth movement of player 1. This makes the game impossible to play as a second player.

I know this is not a problem with my control device. I can switch the devices between the two players and the problem remains with player 2 (it would follow the device to player 1 if it was a fault with the device), and a friend of mine is also experiencing the exact same problem.

I am using a Raspberry Pi 4, running retropie and retroarch and the current build of lr-genesis+gx (commit 3dc6af4 at the time of writing). The device I am testing with is the analog stick of a standard 8bitdo SN30Pro controller.

**Comment by ekeeke** [comment]
I pushed some improvements to Japanese Paddle emulation in my repository which should fix that issue, see https://github.com/ekeeke/Genesis-Plus-GX/commit/6f0ac9a668d73cb541791aaef274d1f3f14e7399

The reason was that previous emulation model handled the automatic "low-nibble/high-nibble" switching of Japanese Paddle by switching it after each read, which works when Paddle is connected to control port #1 as only one I/O read is necessary to get controller data but not when it is connected to control port #2 as two I/O reads are required (so the switching would happen between the two reads)

**Comment by Widge-5** [comment]
Thank you @ekeeke 
I pushed your commit with the improvements to my own fork of the libretro repo in order to test.  And I can confirm that it does fix the issue.  Hopefully this will filter down from your repo to libretro before too long.
Thanks again.

**Comment by ds22x** [comment]
Pulled through https://github.com/libretro/Genesis-Plus-GX/commit/31add24676ba2f2401ff68e4d10cea05b8666ac0
