### ISSUE TITLE
Black Screen - Shin Souseiki Ragnacenty (Japan), worked on 9a9eec1

### ISSUE THREAD

**Issue by waitingmoon** [libretro/Genesis-Plus-GX#344]
Shin Souseiki Ragnacentry (Japan) is not working on [b38cdca](https://github.com/libretro/Genesis-Plus-GX/commit/b38cdca9036332c1b7b05817432d1fd42d59527b). After Sega logo appears, whole of screen goes to black screen. It worked on [9a9eec1](https://github.com/libretro/Genesis-Plus-GX/commit/9a9eec1ee25159969ff83abef956501ec91ee988).

OS: Windows 11 Pro 64bit
RA: 1.17 Git a3efe9c0

**Comment by ekeeke** [comment]
After some investigation, it appears this is caused by a flaw in VDP FIFO emulation, that was not triggered before but got exposed after getting CPU and DMA timings more accurate as this slightly modified game execution timings. Technically, with existing VDP FIFO implementation, when switching between H32 and H40 mode, it could lead to an invalid VDP access slot determination next time VDP FIFO is advanced, which can result in trying to read from FIFO timings array outside of its bounds (memory overflow) when determining the next FIFO access cycle value and, by extension, causes CPU cycle counter to be set to an undetermined value and eventually locks the emulation loop. 

I slightly improved FIFO emulation in https://github.com/ekeeke/Genesis-Plus-GX/commit/6972a5b0d69f633e5ee21d97c9b1068f7147c7db, to be more robust to edge cases like this (and slightly optimize it as well), which fixes the issue in this game.
