### ISSUE TITLE
Thunder Storm FX does not work.

### ISSUE THREAD

**Issue by nanitaro** [libretro/Genesis-Plus-GX#347]
Thunder Storm FX does not work on Genesis-Plus-GX v1.7.4 b063aa8.
It does not progress from the point where the CD-ROM is loaded and the SEGA logo appears.

*Kega Fusion v3.64 is confirmed to work.
*The title of the US version is "Cobra Command", but it is not confirmed to work.

Is there any other information you need?

**Comment by KamiLordus** [comment]
I suggest reporting bugs here:
https://github.com/ekeeke/Genesis-Plus-GX/issues
Because no one looks here, I guess.
I confirm that Thunder Storm FX (Japan) does not work.

**Comment by ekeeke** [comment]
Seems to be fixed by last upstream commit (which fixed missing sprites in Radical Rex intro): https://github.com/ekeeke/Genesis-Plus-GX/commit/dd619513a4a7136e7279cbf6adb660ac30598bdd

The SEGA logo still stays a bit long (if you activate CD leds in Wii emulator version, you can see the game takes some time to read from disc) but it does not lock anymore

https://github.com/libretro/Genesis-Plus-GX/assets/717091/5fcfb630-2def-412e-8218-561888c43320

**Comment by nanitaro** [comment]
Thank you very much.
I was able to confirm the operation to the ending.

Enter debug mode ( up, down, left, right, B, C, A on the title menu screen).
When I set Stage to 10 and Number to 8 and press A, it hangs up.
Perhaps it is the same on the actual device, but I am reporting it.
