### ISSUE TITLE
EA 4-Way Play doesn't work with EA 4-way supported titles (Sega-CD Only)

### ISSUE THREAD

**Issue by sweatypickle** [libretro/Genesis-Plus-GX#46]
Selecting EA 4-Way Play on any any/all inputs does not work with the three EA Sega CD 4-way play specific titles.  If selected, no inputs work.  These are the affected titles.
                  Bill Walsh College Football (Sega CD)
                  FIFA International Soccer (Sega CD)
                  NHL '94 (Sega CD)

Sega Team Player configurations and tiles work correctly for both Genesis and Sega CD.
EA 4-Way play configurations with Genesis titles work correctly.
Oddly, selecting any option of EA 4-way play and the single Sega CD title built for EA or Sega's hardware (ESPN National Hockey Night) works correctly.

**Comment by ekeeke** [comment]
Make sure you don't emulate 6-buttons pad with these games, I don't think they support it through EA 4-Way Play, only 3-buttons pad.

Input devices emulation is common to all emulated system so it makes no difference if the game is for Genesis or Sega CD, it works exactly the same. There could be some emulation incompatibility with some specific games but I doubt it since all these games use the same standard routines to access the multitap.

**Comment by sweatypickle** [comment]
3 or 6 with 4-Way Play still doesn't work.  There's only 3 EA Sega CD titles that support 4-Way Play and one title that supports both.  It's definitely an odd issue.  As an aside, 6-Button with 4-way does work on standard Genesis roms. I'll continue to fiddle and see if I can find anything more to provide.

**Comment by ekeeke** [comment]
Yes, it appears that my 4-way play emulation is not fully accurate, it is good enough to work with the detection routine used in Genesis games (because that's what I have used to reverse-engineer it at these times) but for some reason, those Sega CD games use different startup routine and expect the EA multitap to be fully compatible with normal gamepad protocol at the beginning, which I was not aware it was capable of (probably to handle the fact Sega CD games go through BIOS startup first).

**Comment by ekeeke** [comment]
Fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/23e8ff387e6774234a69deeac85d9492ce4372f6
