### ISSUE TITLE
Sega CD consistently loading wrong bios?

### ISSUE THREAD

**Issue by futurepr0n** [libretro/Genesis-Plus-GX#55]
Hi, basically trying to x-post an issue I am having where Retroarch when trying to load Genesis Plus Core is consistently failing (OSX), and trying to load it from a different region.

https://github.com/libretro/RetroArch/issues/3598

Basically, everything is loading up as follows

![](https://cloud.githubusercontent.com/assets/478986/18558679/f6b5401e-7b41-11e6-9d62-32d4c9583e05.png)

I have tried several roms (same game) from different rom sets, and always getting the same problem. I have also verified my assets for the megacd bios are correct:

```
MD5 (bios_CD_E.bin) = e66fa1dc5820d254611fdcdba0662372
MD5 (bios_CD_J.bin) = 2efd74e3232ff260e371b99f84024f7f
MD5 (bios_CD_U.bin) = 278a9397d192149e84e820ac621a8edd
```

Is there anyway I can produce a log of how Genesis Plus is being loaded up in order to help diagnose the issue? I have been successful loading the rom in another frontend like OpenEmu, and I have also tried setting the region manually after the default auto settings were not working, but this had no effect.

**Comment by ekeeke** [comment]
That message happens when console region is set to USA and BIOS is from a japanese Mega CD.

This means your BIOS labeled as bios_CD_U.bin is actually a japanese BIOS. You can actually open the bin file in an hexeditor and verify the header (or copypaste it here).

I have no idea what are these MD5 values or if there are correct, just get whatever US Sega CD bios (model does not matter) and rename it BIOS_CD_U.bin. Also make sure system region is set to AUTO is core settings and not JAPAN.

**Comment by ekeeke** [comment]
According to https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files
MD5 should be:

```
BIOS_CD_J.bin	278a9397d192149e84e820ac621a8edd
BIOS_CD_U.bin	2efd74e3232ff260e371b99f84024f7f
```

but in the snapshot you posted in https://github.com/libretro/RetroArch/issues/3598 you have

```
BIOS_CD_U.bin	278a9397d192149e84e820ac621a8edd
BIOS_CD_J.bin	2efd74e3232ff260e371b99f84024f7f
```

so it's not really surprising you have trouble loading Sega CD games considering you inverted J and U bios files...

**Comment by futurepr0n** [comment]
I feel so dumb, thanks alot. I did not realize I mislabelled the bios' Thank you for spotting that. Everything works perfect now
