### ISSUE TITLE
linux fullscreen mouse as light gun

### ISSUE THREAD

**Issue by goodjaerb** [libretro/Genesis-Plus-GX#60]
When my mouse is on the left side of the play area, the gun cursor is right on. As I move the mouse to the right, the gun cursor trails behind more and more. This screenshot doesn't show the mouse cursor so you'll have to take my word for it I guess, but it is all the way to the right, yet you can see the gun crosshair hasn't moved as far to match it.
 
![gangster town usa europe -161108-141859](https://cloud.githubusercontent.com/assets/23344536/20114369/02d17110-a5c2-11e6-8f0d-c02398eec8b3.png)

It works fine if I run in windowed mode, which lead me to believe it is related to fullscreen resolution scaling. Seemingly noteworthy also is that it works fine in Retroarch for Windows at fullscreen.

**Comment by ekeeke** [comment]
Neither the core or libretro port can make any difference between windowed or fullscreen modes since this is transparent to them (this is exclusively handled by the frontend) so this is likely another bug or limitation in the input driver implementation of RETRO_POINTER device (which Genesis Plus GX libretro port is using as input device to emulate lightguns).

**Comment by goodjaerb** [comment]
Thanks for the reply! I haven't tested it in probably a year since I made this post. I'll have to test again maybe something changed or I can dig further into what's going on.

**Comment by goodjaerb** [comment]
By the way, I just tried it again and the mouse is working! There has surely been a lot of updates in the last year so something must've done it. Thanks.

**Comment by ekeeke** [comment]
Could you please close the issue, then ?


Envoyé depuis mon smartphone Samsung Galaxy.
null
