### ISSUE TITLE
Wrong aspect ratio for sega Master system games

### ISSUE THREAD

**Issue by budtz** [libretro/Genesis-Plus-GX#61]
It seems i get the wrong aspect ratio for sms games. I have to manually set retroarch for 16:10 to make it correct. Ginisys games are fine.

**Comment by ekeeke** [comment]
SMS games never were "full screen", they only have 192 active lines so there was visible borders on top/bottom of the screen, which make games looking a bit squished (even more on PAL systems)

**Comment by sergiobenrocha2** [comment]
I'm getting 355x192 with PAL roms, like 'Sonic The Hedgehog 2 (Europe) (Rev 1)':

![image](https://cloud.githubusercontent.com/assets/5431285/23289734/a1dfa12a-fa2a-11e6-888f-1a9762b989f9.png)

![image](https://cloud.githubusercontent.com/assets/5431285/23289735/a4d65f36-fa2a-11e6-8bb9-5a021b39f71d.png)

Using Aspect Ratio = Core provided and Core-provided aspect ratio = auto

**Comment by ekeeke** [comment]
As said above, that's correct aspect ratio for PAL (50hz) Master System. The wider horizontal resolution is due to Retroarch upscaling core-provided width (256 pixels) to match core-provided aspect ratio (1.842) without changing core-provided height (192 lines). On a 50hz TV, those 192 lines would rather look downscaled compared with a 60hz TV but here the output is a window and retroarch does not downscale height (you could however enable top/bottom borders to increase window height and reduce its width to something more natural)

If you want NTSC (60hz) aspect ratio, you can force it in core settings.
