### ISSUE TITLE
MultiTap Doesn't Work For All Games

### ISSUE THREAD

**Issue by newoski** [libretro/Genesis-Plus-GX#64]
Hi Guys,

First, thanks for everything you do. With that out of the way, I think I have come across a bug in the Genesis core. 

Put simply, I think the multitap functionality for a number of games is currently broken. 

I've spent the last few days setting up per game overrides to enable MultiTap for all supported Sega Genesis games. While I have been able to get 55 games working, there are still a  number of games that I haven't been able to get MultiTap working -- via any combination of P1 / P2 / EA4Way / TeamPlayer / 6 Button / 3 Button. 

I already submitted this to ekeeke, but he closed the issue indicating that it works on his end. I've tested his recommended setting on RetroArch, for the example game I reported, and they don't seem to work:

https://github.com/ekeeke/Genesis-Plus-GX/issues/116#issuecomment-264658779

That said, here's the full list of games that I've been unable to get working with MultiTap:

Wayne Gretzky and the NHLPA All-Stars
ATP Tour
College Slam
Dino Dini's Soccer
Ichidant-R
International Rugby
J.League Pro Striker 2, 
J.League Pro Striker Perfect Edition
Pro Striker Final Stage
Micro Machines 2 
Mortal Kombat 3
NBA Action 94
NCAA Final Four Basketball
Olympic Gold
Pepen ga Pengo
Ultimate Soccer
Wimbledon
World Cup USA 94
Worms

Finally, if it is at all helpful, I've included a DropBox link below to a zip file containing all of my 55 working Per Game Config Overrides. These config overrides contain nothing but the changes required to get MultiTap working on the games that do, in fact, work. 

https://www.dropbox.com/s/0pdus1rj12thbd2/Sega%20Genesis%20-%20Working%20MultiTap%20Per%20Game%20Config%20Overrides.zip?dl=0

Thanks!

**Comment by ekeeke** [comment]
>Wayne Gretzky and the NHLPA All-Stars
 
see https://github.com/ekeeke/Genesis-Plus-GX/issues/116#issuecomment-264689857

>ATP Tour
![retroarch-1204-085815](https://cloud.githubusercontent.com/assets/717091/20864939/7ac7d4ba-ba04-11e6-8969-f4c978b05eb5.png)

>College Slam
Works fine with Teamplayer in either port 1 or port 2.
You need to press A on each controller to activate them in the team selection screen (can't do it in retroarch since I only have a keyboard but here is a screenshot of standalone version showing 4 controllers detected)
![collegeslam](https://cloud.githubusercontent.com/assets/717091/20864945/ae112506-ba04-11e6-89a0-8321c7ab05aa.jpg)

>Dino Dini's Soccer
Works fine with gamepad in port 1 and Teamplayer in port 2
![retroarch-1204-094057](https://cloud.githubusercontent.com/assets/717091/20864980/c34a04f0-ba05-11e6-8931-e00133fe7bfe.png)

>Ichidant-R
Works fine with gamepad in port 1 and Teamplayer in port 2
![retroarch-1204-125855](https://cloud.githubusercontent.com/assets/717091/20865989/6f8d8bfe-ba21-11e6-8972-fa8d5dcaf4cb.png)

>International Rugby
Support 1-2 Player only
http://segaretro.org/images/d/d6/InternationalRugby_MD_EU_Box.jpg

>J.League Pro Striker 2
Works fine with gamepad in port 1 and Teamplayer in port 2
![retroarch-1204-130503](https://cloud.githubusercontent.com/assets/717091/20866032/842f6a18-ba22-11e6-9224-59889a51659e.png)

>J.League Pro Striker Perfect Edition
Works fine with gamepad in port 1 and Teamplayer in port 2
![retroarch-1204-134302](https://cloud.githubusercontent.com/assets/717091/20866204/95196cd4-ba27-11e6-9dae-8a193805da64.png)

>Pro Striker Final Stage
Works fine with gamepad in port 1 and Teamplayer in port 2
![retroarch-1204-135105](https://cloud.githubusercontent.com/assets/717091/20866243/b6fc205c-ba28-11e6-9356-0ab545801529.png)

>Micro Machines 2
Only version without jcart supports teamplayer adapter, not sure if it was dumped but could not find it

>Mortal Kombat 3

**Comment by ekeeke** [comment]
These games work fine for me (at least those which really have multitap support, some of this list don't). Tested in retroarch with windows dll compiled from my repository 
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/builds/genesis_plus_gx_libretro.dll

**Comment by ekeeke** [comment]
Don't forget to close this,  there are already too much non- or fixed issues left open in this repository.
Thanks

**Comment by newoski** [comment]
Will do as soon as I get home to test.

**Comment by newoski** [comment]
Hi ekeeke, 

My sincerest thanks for your help getting this setup. Thanks to your help, I've got all supported MultiTap games for Sega Gensis working via the Genesis Plus GX core. 

As a shortcut for anyone else that wants to setup all games, here is a link to my Per Game Config Overrides. Just enable Per Game Config Overrides and merge the attached folder structure with your own RetroArch folder. It contains no changes other than the MultiTap enabled settings. 

https://www.dropbox.com/s/kjjzo83dfb7laee/Sega%20Genesis%20MultiTap%20Per%20Game%20Config%20Overrides.zip?dl=0

Cheers and thanks again!
